
USE LLM_DATA;

/**
DROP TABLE BROWSER_REQUEST;
DROP TABLE LLM_REQUEST;
DROP TABLE MCP_CALL_REQUEST;
**/

/** 프롬프트 로그 **/
CREATE TABLE IF NOT EXISTS LLM_DATA.LOG_PROMPT_REQUEST
(    
	NO INT AUTO_INCREMENT PRIMARY KEY,
    AGENT_ID SMALLINT DEFAULT 0,
    PROMPT TEXT NOT NULL,
    REG_DATE VARCHAR(64) DEFAULT '',	
	SESSION_ID VARCHAR(128) DEFAULT '',
	USER_ROLE VARCHAR(128) DEFAULT '',
    ALLOWED SMALLINT DEFAULT 1,
    MODIFIED_PROMPT TEXT DEFAULT '',    
    REASON VARCHAR(64) DEFAULT ''
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/** 프롬프트 추가 쿼리 **/
/**
INSERT INTO LLM_DATA.LOG_PROMPT_REQUEST (AGENT_ID, PROMPT, REG_DATE, SESSION_ID, USER_ROLE, ALLOWED, MODIFIED_PROMPT, REASON)
VALUES (100, '혹시 python의 fast api 의 model에서 list는 어떻게 표현하나요', '2025-09-16 12:18:46', 'dc677ee2118504418d96e47ce29e48591d701d871d40388992e1af332e9d2874', '기술전략실', 1, '', '');

**/


/** MCP 서버 차단 로그 **/
CREATE TABLE IF NOT EXISTS LLM_DATA.LOG_MCP_SERVER_BLOCK
(    
	NO INT AUTO_INCREMENT PRIMARY KEY,
    SERVER_NAME VARCHAR(256) DEFAULT '',
    TOOL_NAME VARCHAR(256) DEFAULT '',
    REG_DATE VARCHAR(64) DEFAULT '',
    REG_TYPE SMALLINT 2 DEFAULT 0,
    ETC_COMMENT VARCHAR(256) DEFAULT '',
    ALLOWED SMALLINT DEFAULT 1,
    REASON VARCHAR(64) DEFAULT ''    
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/** 사용자 행위 로그 **/
CREATE TABLE IF NOT EXISTS LLM_DATA.LOG_USER_MONITOR
(    
	NO INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(128) NOT NULL,
    SESSION_ID VARCHAR(256) DEFAULT '',
    REG_DATE VARCHAR(64) DEFAULT '',
    ETC_COMMENT VARCHAR(256) DEFAULT '',
    ALLOWED SMALLINT DEFAULT 1,
    REASON VARCHAR(64) DEFAULT ''       
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/** 감사로그 **/
CREATE TABLE IF NOT EXISTS LLM_DATA.LOG_AUDIT
(    
	NO INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(128) NOT NULL,
    SERVER_IP VARCHAR(64) NOT NULL,
    REG_DATE VARCHAR(64) DEFAULT '',
    AUDIT_MESSAGE TEXT DEFAULT '',
    AUDIT_TYPE INT DEFAULT 0,
    ETC_COMMENT VARCHAR(256) DEFAULT ''
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*
CREATE TABLE IF NOT EXISTS LLM_DATA.LLM_REQUEST
(    
    NO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AGENT_ID INTEGER DEFAULT 0,
    REG_DATE TEXT DEFAULT '',    
	MESSAGES TEXT NOT NULL,
	LLM_KEY TEXT NOT NULL,
	ITERATION INTEGER NOT NULL,
    STREAM INTEGER DEFAULT 0,
    ALLOWED INTEGER DEFAULT 0,
    MODIFIED_QUERY TEXT DEFAULT '',
    SOURCE TEXT DEFAULT ''
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
*/

/*
CREATE TABLE IF NOT EXISTS LLM_DATA.MCP_CALL_REQUEST
(    
    NO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AGENT_ID INTEGER DEFAULT 0,
    REG_DATE TEXT DEFAULT '',    
    SERVER_NAME TEXT NOT NULL,
	TOOL_NAME TEXT NOT NULL,	
    ARGUMENTS TEXT DEFAULT '',
    ALLOWED INTEGER DEFAULT 0,        
    SOURCE TEXT DEFAULT ''
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
*/

COMMIT;