
USE LLM_POLICY;

/* 사용자 계정 AI에서 수집된 계정, 가안으로 생성 */
CREATE TABLE IF NOT EXISTS APP.AI_USER_ACCOUNT
(
    USER_ID VARCHAR(128)  PRIMARY KEY,
    REG_DATE VARCHAR(64)  DEFAULT '',
    EMAIL VARCHAR(256)  DEFAULT '',
    AI_SERVICE SMALLINT  DEFAULT 0,
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    USE_FLAG SMALLINT DEFAULT 1
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/* 사용자 계정 관리*/
CREATE TABLE IF NOT EXISTS LLM_POLICY.USER_ACCOUNT
(
    USER_ID VARCHAR(128)  PRIMARY KEY,
    USER_PASSWD VARCHAR(256)  NOT NULL,
    PASSWD_SALT VARCHAR(256)  DEFAULT '',
    REG_DATE VARCHAR(64)  DEFAULT '',
    EMAIL VARCHAR(256)  DEFAULT '',
    DEPT VARCHAR(128)  DEFAULT '',
    TEL VARCHAR(64)  DEFAULT '',
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    SESSION_ID VARCHAR(256)  DEFAULT '',
    LOGIN_STATUS SMALLINT  DEFAULT 0,
    MODIFY_DATE VARCHAR(256)  DEFAULT '',
    LIMIT_DATE VARCHAR(256)  DEFAULT '',
    GROUP_ID INT  DEFAULT 0,
    ROLE_ID INT  DEFAULT 0,
    USE_FLAG SMALLINT DEFAULT 1
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE ADD COLUMN GROUP_ID INT DEFAULT 0;

ALTER TABLE LLM_POLICY.USER_ACCOUNT ADD COLUMN IF NOT EXISTS GROUP_ID INT DEFAULT 0;
ALTER TABLE LLM_POLICY.USER_ACCOUNT ADD COLUMN IF NOT EXISTS ROLE_ID INT DEFAULT 0;
ALTER TABLE LLM_POLICY.USER_ACCOUNT ADD COLUMN IF NOT EXISTS USE_FLAG INT DEFAULT 1;

/** 사용자 계정 추가 쿼리 **/
/**
INSERT INTO LLM_POLICY.USER_ACCOUNT (USER_ID, USER_PASSWD, PASSWD_SALT, REG_DATE, EMAIL, DEPT, TEL, ETC_COMMENT, SESSION_ID, LOGIN_STATUS, MODIFY_DATE, LIMIT_DATE)
VALUES ('root001', 'dc677ee2118504418d96e47ce29e48591d701d871d40388992e1af332e9d2874', 'root001#Sniper_01', '2025-09-16 12:18:46', 'ghahn@wins21.co.kr', '기술전략실', '010-0000-0000', '', '', 1, '', '');

UPDATE LLM_POLICY.USER_ACCOUNT SET GROUP_ID = 1000 WHERE USER_ID = 'root001'
**/

/* 그룹 관리 */
CREATE TABLE IF NOT EXISTS LLM_POLICY.USER_GROUP
(
    GROUP_ID INT PRIMARY KEY,
    GROUP_NAME VARCHAR(128) NOT NULL UNIQUE,
    REG_DATE VARCHAR(64)  DEFAULT '',
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    USE_FLAG SMALLINT DEFAULT 1
);

/** 그룹 추가 쿼리 **/
/**
INSERT INTO LLM_POLICY.USER_GROUP (GROUP_ID, GROUP_NAME, REG_DATE, USE_FLAG)
VALUES (1000, 'default_group', '2025-09-22 10:18:46', 1);

UPDATE LLM_POLICY.USER_GROUP SET GROUP_NAME = '기술전략실' WHERE GROUP_ID = 1000
**/


/* 권한 관리 */
CREATE TABLE IF NOT EXISTS LLM_POLICY.USER_ROLE
(
    ROLE_ID INT PRIMARY KEY,
    ROLE_NAME VARCHAR(128) NOT NULL UNIQUE,
    ROLE_AUTH INT NOT NULL,
    REG_DATE VARCHAR(64)  DEFAULT '',
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    USE_FLAG SMALLINT DEFAULT 1
);

/* 필터뷰 */
CREATE TABLE IF NOT EXISTS LLM_POLICY.FILTER_VIEW_INFO
(
    NO INT AUTO_INCREMENT PRIMARY KEY,
    /**NO INT AUTO_INCREMENT PRIMARY KEY,**/
    TYPE_ID SMALLINT NOT NULL,
    FILTER_NAME VARCHAR(128) NOT NULL,
    REG_DATE VARCHAR(64)  DEFAULT '',
    FILTER_CONDITION TEXT  DEFAULT '',
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    USE_FLAG SMALLINT DEFAULT 1
);

/** 필터뷰 추가 쿼리 **/
/**
INSERT INTO LLM_POLICY.FILTER_VIEW_INFO (VIEW_ID, TYPE_ID, FILTER_NAME, REG_DATE, FILTER_CONDITION, USE_FLAG)
VALUES (1, 1, 'filterview 테스트', '2025-09-22 10:18:46', '', 1);

**/


/******************************************************* 정책 관리 ***/

/* MCP 서버 목록 */
CREATE TABLE IF NOT EXISTS LLM_POLICY.MCP_SERVER_INFO
(
    NO INT AUTO_INCREMENT PRIMARY KEY,
    SERVER_NAME VARCHAR(256) NOT NULL,
    TOOL_NAME VARCHAR(256) NOT NULL,
    URL VARCHAR(512) DEFAULT '',
    REG_TYPE SMALLINT NOT NULL,
    REG_DATE VARCHAR(64)  DEFAULT '',    
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    USE_FLAG SMALLINT DEFAULT 1
);

/* 정책 카테고리 */
CREATE TABLE IF NOT EXISTS LLM_POLICY.SYSTEM_CATEGORY
(
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(256) NOT NULL,
    CATEGORY_TYPE INT NOT NULL,
    ETC_FREEVALUE VARCHAR(512) DEFAULT '',    
    REG_DATE VARCHAR(64)  DEFAULT '',    
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    USE_FLAG SMALLINT DEFAULT 1
);

/* 프롬프트 키워드 정책 */
CREATE TABLE IF NOT EXISTS LLM_POLICY.PROMPT_KEYWORD_POLICY
(
    POLICY_ID INT PRIMARY KEY,
    CATEGORY_ID VARCHAR(256) NOT NULL,
    PROMPT_KEYWORD TEXT DEFAULT '',    
    REG_DATE VARCHAR(64)  DEFAULT '',    
    REG_TYPE SMALLINT DEFAULT 1,
    RISK_LEVEL SMALLINT DEFAULT 0,
    ETC_COMMENT VARCHAR(256)  DEFAULT '',
    USE_FLAG SMALLINT DEFAULT 1
);


COMMIT;




